/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.jupiter.api.Test;

import calculator.shapes.*;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;


class ShapeTest {

    private Circle test_circle;
    private Square test_square;
    private RegularHexagon test_hexagon;
    private Rectangle test_rectangle;
    private Triangle test_triangle;


    @BeforeEach
    void setUp() throws Exception{
        // Setup all our shapes 

        // One Dimension Shapes
        int[] our_dimension = new int[1];
        our_dimension[0] = 10;

        int[] our_dimensions = new int[2];
        our_dimensions[0] = 10;
        our_dimensions[1] = 20;

        test_circle = new Circle(our_dimension);
        test_square = new Square(our_dimension);
        test_hexagon = new RegularHexagon(our_dimension);
        test_rectangle = new Rectangle(our_dimensions);
        test_triangle = new Triangle(our_dimensions);
    }

    @Test
    @DisplayName("Test all shape areas")
    void test_get_areas(){
        assertAll("Areas",
            () -> assertEquals(100.0, test_square.calculate_area()),
            () -> assertEquals(200.0, test_rectangle.calculate_area()),
            () -> assertEquals(260.0, test_hexagon.calculate_area()),
            () -> assertEquals(314.1592653589793, test_circle.calculate_area()),
            () -> assertEquals(100.0, test_triangle.calculate_area())  
        );
    }

    @Test
    @DisplayName("Test all shape dimension displays")
    void test_dimensions(){
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));
        
        test_square.dimensions();
        test_circle.dimensions();
        test_hexagon.dimensions();
        test_triangle.dimensions();
        test_rectangle.dimensions();

        String actual_output = new String(outContent.toByteArray());

        assertTrue(actual_output.contains("The side-length is: 10"));
        assertTrue(actual_output.contains("The radius is: 10"));
        assertTrue(actual_output.contains("The length is: 10"));
        assertTrue(actual_output.contains("The width is: 20"));
        assertTrue(actual_output.contains("The base is: 10"));
        assertTrue(actual_output.contains("The height is: 20"));
    }

    @Test
    void teardown() throws Exception{
        test_circle = null;
        test_square = null;
        test_hexagon = null;
        test_rectangle = null;
        test_triangle = null;

        assertNull(test_circle);
        assertNull(test_square);
        assertNull(test_hexagon);
        assertNull(test_rectangle);
        assertNull(test_triangle);
    }

}
